GameShop/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace GameShop.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GameShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>@ViewBag.Title</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container mt-4>
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Game store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @if (User.Identity!.IsAuthenticated && (User.IsInRole("user") || User.IsInRole("admin")))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Магазин
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="GamesInShop" asp-action="Index">Все игры магазина</a></li>
                                <li><a class="dropdown-item" asp-controller="GamesInShop" asp-action="PopularGames">Популярное</a></li>
                                <li><a class="dropdown-item" asp-controller="GamesInShop" asp-action="RecommendationGames">Рекомендации</a></li>
                                <li><a class="dropdown-item" asp-controller="GamesInShop" asp-action="WishList">Список желаемого</a></li>
                            </ul>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Library" asp-action="Index">Библиотека</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Profile" asp-action="Index">Профиль</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">Выйти из аккаунта</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Войти</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
                        </li>
                    }
                </ul>
                @if (User.Identity!.IsAuthenticated && (User.IsInRole("user") || User.IsInRole("admin")))
                {
                    <form class="d-flex">
                        <a asp-controller="Cart" asp-action="Index" class="btn btn-success">Корзина</a>
                    </form>
                }
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        @RenderBody()
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>